# Generated by Django 6.1 on 2026-08-17 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Exam Title (e.g. Data Structures Midterm)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Instructions or exam description')),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Exam duration in minutes')),
                ('total_marks', models.PositiveIntegerField(default=100, help_text='Total marks for the exam')),
                ('pass_marks', models.PositiveIntegerField(default=40, help_text='Passing marks required')),
                ('is_published', models.BooleanField(default=False, help_text='If published, students can view and attempt this exam')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Teacher who created this exam', on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Question statement')),
                ('marks', models.PositiveIntegerField(default=1, help_text='Marks for this question')),
                ('order', models.PositiveIntegerField(default=1, help_text='Question sequence order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(help_text='Option answer text', max_length=500)),
                ('is_correct', models.BooleanField(default=False, help_text='Mark True if this is the correct answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.question')),
            ],
        ),
    ]
